### ISSUE TITLE
Incompatible with 2023.1 EAP

### ISSUE THREAD

**Issue by juherr** [AleksandrSl/intellij-browserslist#12]
Hi,

The plugin doesn't work with the current IntelliJ EAP version (2023.1).

Do you have a repository for EAP releases?

**Comment by AleksandrSl** [comment]
Hi, interesting, didn't get the notification about incompatibilities. I will check what's wrong today and publish a new version.

**Comment by juherr** [comment]
For the record:
```
IntelliJ IDEA 2023.1 EAP (Ultimate Edition)
Build #IU-231.5920.14, built on January 27, 2023
```

<img width="279" alt="image" src="https://user-images.githubusercontent.com/254697/215538382-f70b9edf-2565-46d3-a9c6-9d5f812795ff.png">

**Comment by AleksandrSl** [comment]
For some reason I missed that I can not specify `untilBuild` version. Removed the upper version bound in 1.0.2, will test it tomorrow on the WS 2023.1 EAP (run out of internet to download it :cry: )

**Comment by AleksandrSl** [comment]
[New plugin version](https://plugins.jetbrains.com/plugin/16139-browserslist/versions/stable) is approved. Should be compatible with 223 builds

**Comment by juherr** [comment]
Got it. Thanks
